# image options
image_size: 224
dataset: "PICKPLACECONTEXT"
n_view_points: 2

# model options
method : "contrastive"
network: "resnet50"
out_features: 32
projection_dim: 64 # "[...] to project the representation to a 128-dimensional latent space"
model_path: "../results" 
epochs: 1000
batch_size: 32
margin : 2.0
normalize: True